;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attack.Secondary",DevComment="")
+GameplayTagList=(Tag="Attack.Standard",DevComment="")
+GameplayTagList=(Tag="Character.MaxHealth",DevComment="")
+GameplayTagList=(Tag="Character.Player",DevComment="")
+GameplayTagList=(Tag="Combat.Attack",DevComment="")
+GameplayTagList=(Tag="Combat.CleaveAttack",DevComment="")
+GameplayTagList=(Tag="Combat.Dodge",DevComment="")
+GameplayTagList=(Tag="Combat.InCombat",DevComment="")
+GameplayTagList=(Tag="Combat.RangeAttack",DevComment="")
+GameplayTagList=(Tag="EquipmentStatBuffs",DevComment="")
+GameplayTagList=(Tag="EquipmentStatBuffs.Attack",DevComment="")
+GameplayTagList=(Tag="EquipmentStatBuffs.Control",DevComment="")
+GameplayTagList=(Tag="EquipmentStatBuffs.Defense",DevComment="")
+GameplayTagList=(Tag="EquipmentStatBuffs.MaxHealth",DevComment="")
+GameplayTagList=(Tag="EquipmentStatBuffs.Power",DevComment="")
+GameplayTagList=(Tag="EquipmentStatBuffs.Vigor",DevComment="")
+GameplayTagList=(Tag="Equipped",DevComment="")
+GameplayTagList=(Tag="Equipped.Accessory01",DevComment="")
+GameplayTagList=(Tag="Equipped.Accessory02",DevComment="")
+GameplayTagList=(Tag="Equipped.Arms",DevComment="")
+GameplayTagList=(Tag="Equipped.Chest",DevComment="")
+GameplayTagList=(Tag="Equipped.Legs",DevComment="")
+GameplayTagList=(Tag="Equipped.Weapon",DevComment="")
+GameplayTagList=(Tag="Event.Cooldown",DevComment="")
+GameplayTagList=(Tag="Event.Cooldown.Dodge",DevComment="")
+GameplayTagList=(Tag="Event.Damage",DevComment="")
+GameplayTagList=(Tag="Event.Death",DevComment="")
+GameplayTagList=(Tag="Event.HealthChange",DevComment="")
+GameplayTagList=(Tag="Event.HealthFull",DevComment="")
+GameplayTagList=(Tag="Event.XPReward",DevComment="")
+GameplayTagList=(Tag="Feedback.Blocked",DevComment="Attack was blocked")
+GameplayTagList=(Tag="Feedback.Death",DevComment="Enemy or player died")
+GameplayTagList=(Tag="Feedback.Hit.Crit",DevComment="Critical strike")
+GameplayTagList=(Tag="Feedback.Hit.Melee",DevComment="Standard melee hit")
+GameplayTagList=(Tag="Feedback.Hit.RangedAttack",DevComment="Hit with projectile")
+GameplayTagList=(Tag="Foley",DevComment="")
+GameplayTagList=(Tag="Foley.Event",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Handplant",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Jump",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Land",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Run",DevComment="")
+GameplayTagList=(Tag="Foley.Event.RunBackwds",DevComment="")
+GameplayTagList=(Tag="Foley.Event.RunStrafe",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Scuff",DevComment="")
+GameplayTagList=(Tag="Foley.Event.ScuffPivot",DevComment="")
+GameplayTagList=(Tag="Foley.Event.ScuffWall",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Tumble",DevComment="")
+GameplayTagList=(Tag="Foley.Event.Walk",DevComment="")
+GameplayTagList=(Tag="Foley.Event.WalkBackwds",DevComment="")
+GameplayTagList=(Tag="LevelUp",DevComment="")
+GameplayTagList=(Tag="LevelUp.AddSkillpoints",DevComment="")
+GameplayTagList=(Tag="LevelUp.Control",DevComment="")
+GameplayTagList=(Tag="LevelUp.ElementalAttack",DevComment="")
+GameplayTagList=(Tag="LevelUp.ElementalDefense",DevComment="")
+GameplayTagList=(Tag="LevelUp.MaxHP",DevComment="")
+GameplayTagList=(Tag="LevelUp.PhysAttack",DevComment="")
+GameplayTagList=(Tag="LevelUp.PhysDefense",DevComment="")
+GameplayTagList=(Tag="LevelUp.Power",DevComment="")
+GameplayTagList=(Tag="LevelUp.Vigor",DevComment="")
+GameplayTagList=(Tag="Status.Invincible",DevComment="")
+GameplayTagList=(Tag="UI.Layer",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.LoadingScreen",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="")
+GameplayTagList=(Tag="UI.Layer.SubModal",DevComment="")

